[book]
title = "Runix"
authors = ["Kiril"]
language = "ru"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
no-section-label = true

smart-punctuation = false
git-repository-url = "https://github.com/Kileer20100/Runix"
sidebar-header-nav = true
